# Generated by Django 2.2.1 on 2019-05-31 23:49

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Numero de Celular', max_length=31),
        ),
    ]
