# Generated by Django 2.2.1 on 2019-06-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190603_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sexo',
            new_name='bornDate',
        ),
    ]
