# Generated by Django 2.2.1 on 2019-06-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190603_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='disability',
        ),
        migrations.AddField(
            model_name='profile',
            name='disability',
            field=models.ManyToManyField(to='users.Disability'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.ManyToManyField(to='users.Language'),
        ),
    ]
