# Generated by Django 2.2.1 on 2019-06-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190603_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disability',
            name='disability',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='language',
            name='dialect',
            field=models.CharField(default='', max_length=30),
        ),
    ]
