# Generated by Django 2.2.1 on 2019-06-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190603_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='dialect',
        ),
    ]
