# Generated by Django 2.2.1 on 2019-06-03 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_language_dialect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disability',
            name='disability',
            field=models.CharField(default='Ninguna', max_length=30),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='disability',
        ),
        migrations.AddField(
            model_name='profile',
            name='disability',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='users.Disability'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='users.Language'),
        ),
    ]
