# Generated by Django 2.2.1 on 2019-06-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190603_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='disability',
            new_name='id_disability',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='language',
            new_name='id_language',
        ),
    ]
