# Generated by Django 2.2.1 on 2019-06-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20190603_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_disability',
            field=models.ManyToManyField(to='users.Disability'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_language',
            field=models.ManyToManyField(to='users.Language'),
        ),
    ]
