# Generated by Django 2.2.1 on 2019-06-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20190603_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disability',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_disability',
            field=models.ManyToManyField(to='users.Disability'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_language',
            field=models.ManyToManyField(to='users.Language'),
        ),
    ]
