# Generated by Django 2.2.1 on 2019-06-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20190603_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_disability',
            new_name='disability',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='id_language',
            new_name='language',
        ),
    ]
