# Generated by Django 2.2.1 on 2019-06-04 02:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20190604_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disability',
            name='disability',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='nombre', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='apellido', max_length=30),
        ),
    ]
